# Generated by Django 5.0.1 on 2026-02-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
